### ISSUE TITLE
Renaming to "fil-blst"?

### ISSUE THREAD

**Issue by vmx** [filecoin-project/fil-blst#6]
Given what this library does, would it make sense to rename it to fil-blst? As it does Filecoin specific optimizations and not Lotus specific ones.

**Comment by porcuquine** [comment]
Agreed — I had the same thought.

**Comment by porcuquine** [comment]
Done.

**Comment by vmx** [comment]
Not done. It needs lots of code changes I'm doing atm.

**Comment by porcuquine** [comment]
Whoops, well repo name is changed — _my work is done_.
