### ISSUE TITLE
Changing license to Apache + MIT

### ISSUE THREAD

**Issue by vmx** [filecoin-project/fil-blst#7]
In the Rust ecosystem it's common to have software dual licensed under Apache 2.0 and MIT (Protocol Labs does the same for it's project). Should be relicense this project as well?

**Comment by porcuquine** [comment]
It's also the standard for `filecoin-project`, so yes.

**Comment by vmx** [comment]
After a second thought. This is mostly about blst, which is Apache 2.0 only. So if we change the license it would only be for the bindings. I'm not sure if it's worth the license change dance. I'd currently vote for "leave it at Apache 2.0 only".

**Comment by vmx** [comment]
I really think it's clearer having this under Apache 2.0 only as the main code (blst) is also under Apache 2.0 only. Hence I'm closing this issue. If anyone disagrees, feel free to re-open.
